[main.blas1]
format = "official"
url = "https://github.com/BrandenEK/Blasphemous.Modding.Installer/raw/main/BlasphemousMods.json"
maintainer = "Damocles"

[main.blas2]
format = "official"
url = "https://github.com/BrandenEK/Blasphemous.Modding.Installer/raw/main/BlasphemousIIMods.json"
maintainer = "Damocles"
