#!/usr/bin/env sh

if [ "$PYTHON_VIRTUALENV_PATH" = "" ]
then
    PYTHON_VIRTUALENV_PATH="$HOME/.local/share/blasmodcli/venv"
fi

. "$PYTHON_VIRTUALENV_PATH/bin/activate"
python3 -m blasmodcli "Blasphemous 2" -- "$@"
